{
  config,
  lib,
  ...
}:
{
  # Colors, fonts, and sizes, all of them following the active stylix scheme.
  wayland.windowManager.jay.settings = {
    show-bar = true;
    show-titles = true;

    theme =
      with config.lib.stylix.colors.withHashtag;
      let
        font = config.stylix.fonts.monospace.name;
      in
      {
        inherit font;
        bg-color = base00;

        border-width = 1;
        border-color = base03;

        title-height = 16;
        title-font = font;
        attention-requested-bg-color = base09;
        captured-focused-title-bg-color = base08;
        captured-unfocused-title-bg-color = base0A;
        focused-inactive-title-bg-color = base03;
        focused-inactive-title-text-color = base05;
        focused-title-bg-color = base0D;
        focused-title-text-color = base00;
        separator-color = base03;
        unfocused-title-bg-color = base03;
        unfocused-title-text-color = base05;
        highlight-color = base0B;

        bar-position = "bottom";
        bar-height = 16;
        bar-separator-width = 1;
        bar-font = font;
        bar-bg-color = base01;
        bar-status-text-color = base05;
      };
  };

  # Read at reload time by the shared library configuration in
  # ../../../../pkgs/jay-config-lib (see its src/theme.rs) instead of being
  # compiled into config.so, so switching stylix schemes does not require
  # rebuilding the config crate. The toml configuration does not read it, it
  # is regenerated by home-manager anyway.
  xdg.configFile."jay/theme.toml".text = lib.concatStrings (
    lib.mapAttrsToList (name: value: "${name} = ${builtins.toJSON (toString value)}\n") {
      cursor_theme = config.home.pointerCursor.name;
      cursor_size = config.home.pointerCursor.size;
      gtk_theme = config.gtk.theme.name;
      qt_platform_theme = config.qt.platformTheme.name;
      qt_style = config.qt.style.name;
      monospace_font = config.stylix.fonts.monospace.name;

      base00 = config.lib.stylix.colors.base00;
      base01 = config.lib.stylix.colors.base01;
      base02 = config.lib.stylix.colors.base02;
      base03 = config.lib.stylix.colors.base03;
      base04 = config.lib.stylix.colors.base04;
      base05 = config.lib.stylix.colors.base05;
      base06 = config.lib.stylix.colors.base06;
      base07 = config.lib.stylix.colors.base07;
      base08 = config.lib.stylix.colors.base08;
      base09 = config.lib.stylix.colors.base09;
      base0a = config.lib.stylix.colors.base0A;
      base0b = config.lib.stylix.colors.base0B;
      base0c = config.lib.stylix.colors.base0C;
      base0d = config.lib.stylix.colors.base0D;
      base0e = config.lib.stylix.colors.base0E;
      base0f = config.lib.stylix.colors.base0F;
    }
  );
}
