// Generated by home/jacobsen/wayland/jay-config/default.nix. Do not edit by hand.
#![allow(dead_code)]

pub const JAY_MODE_SCRIPT: &str = "jay-mode";

pub const CURSOR_THEME: &str = "Adwaita";
pub const CURSOR_SIZE: &str = "24";
pub const GTK_THEME: &str = "Adwaita";
pub const QT_PLATFORM_THEME: &str = "gtk3";
pub const QT_STYLE: &str = "Adwaita";
pub const MONOSPACE_FONT: &str = "monospace";

pub const BASE00: &str = "000000";
pub const BASE01: &str = "111111";
pub const BASE02: &str = "222222";
pub const BASE03: &str = "333333";
pub const BASE04: &str = "444444";
pub const BASE05: &str = "555555";
pub const BASE06: &str = "666666";
pub const BASE07: &str = "777777";
pub const BASE08: &str = "880000";
pub const BASE09: &str = "990000";
pub const BASE0A: &str = "aaaa00";
pub const BASE0B: &str = "00bb00";
pub const BASE0C: &str = "00cccc";
pub const BASE0D: &str = "0000dd";
pub const BASE0E: &str = "ee00ee";
pub const BASE0F: &str = "0f0f0f";
