#ENC[AES256_GCM,data:anjcB37oydkqOk1o2a/iY6T2DYwR+Ae1ZA==,iv:jyxgWtmQwBLO+pPC6U2zxkKa0TAvrD43qoR6RRBCUUE=,tag:XNgqe8wrxLj45XHr/ONsfg==,type:comment]
eduroam:
    identity: ENC[AES256_GCM,data:gqfDBlA/moDT6q311DZiPw==,iv:wswWggy5jhCG1npHjijN5I94ITMDbA84xS7EpWWGzAk=,tag:79GOA9uZmff4d41cfnOKDg==,type:str]
    password: ENC[AES256_GCM,data:TzhgM7vIX5XJsh1fm4zPqfQ9cwQC110OGewfW4c9L5OEGXYeC+ghCvPPaCYhCzGLneI=,iv:AYmVvf/cz1GpSvmyb4xT2jUlCTWtbQ3t5+H3uJVbPAE=,tag:vfVhMvGwAjYxW6cA0OFMqw==,type:str]
#ENC[AES256_GCM,data:tpU8PyOLH7kwQOj1+u2QTTSQdA==,iv:1SGVXMib3Z0wrH2QEvEdN60jcXt97HyRHn9RTtYtgpc=,tag:vYDk246CufcXKyTlhL3fBA==,type:comment]
system:
    #ENC[AES256_GCM,data:f7tgfHfQybKDrD03AQ0j/tA5mvpNLJfzOXDaaoVeaV+6VjC3rRj+58PBWmokg4H4bweqDmtlXZ0RQqL/boICje/WQEX+LTYa6yYJ7I7VZnJFz+6pb7InYA==,iv:ERwKze32QBNqBgkZc3ZUabWXQaGCd73gKkWpF6sNnsY=,tag:FmTaGECxT+ccAbO6y0QVdA==,type:comment]
    password: ENC[AES256_GCM,data:sSg9fZdP1rT5ezZ5unkmJARKbVslV1cX/iPSxm2DpMAHBCLkeknkz0vta2sMOJEzTPuSFFLH7OasZemEUvNko6gv/9f5OVKGWedQkm+FrylW01z0ZtvG+unUlbSJPgQCfN6brFIUb+3byA==,iv:aL5XqIBte+8qFCXGdwzKXehzJECpqVKoUrn2Xv1cLAE=,tag:YPYbnZ9a/HEBVeG8p+lT/A==,type:str]
#ENC[AES256_GCM,data:vZL9PR2dJKoiI0b+Djj1AUW5MQ==,iv:28GM8gTPdmlQT4TgBgpaRpZRBV9JIClEyOg8g/qQQdQ=,tag:RzVBDagU3IHia/d0R4NGwQ==,type:comment]
webdav:
    #ENC[AES256_GCM,data:9cyZUCmghkHIYk4y08/szjq4EZZrH6Amvh5bU4X9zFMJtaEjJEq1k/IdvFu+ETWU3+3YnAqP2MSvX0nwIi065uVp4krFJ4X3nDhjKCrWHxNNnL7M6SKlg1HeqGhx+K7y6Ykc5iDNx438WaBR4g==,iv:erf0JqYfpoMbBRGipY1BLqNrPmm3rT8T7frCGAnYgqI=,tag:5Kpau4jAG/+41rW9/9umVg==,type:comment]
    #ENC[AES256_GCM,data:y9mQl21iWsMts22T5MLuA21ZJgTY2sgkzchcF4eGIYQJWPrKLL9zwQBX0OgsvkjjzfBteXnrC5EZ7qeKgURqLi9yldQhcSbAo/BMpuUABrD4olCt,iv:0eWAD4vjAPm3bjYJK+1v9IhPoDwn2uuJ1wgRR1hRkBI=,tag:52vANbO5AMzKnib+diDLeQ==,type:comment]
    #ENC[AES256_GCM,data:XGrCsNYlYQpq6Hoj0YxaiQDZPcv41BCQgJnwOX8UQWBQRNTbrubhDdmFIY5uj47VvWQeOAYO9o6EDWmLTS4fMpvbuLUEXh+HBg==,iv:KecwPM1LGhgO8S/v0yMh+BLqQTGHxseg2PqF0yAkgtM=,tag:3vhPKWdXrlLphaMD4L3CaA==,type:comment]
    #ENC[AES256_GCM,data:mQtX9fz5xHeGrEEjk1bCntI3+e8wj5g2yhCeR3o285RcmmC7u8KcAv9bKmlzewYFHmBQuq378qwW1fkeM8ALDqWwfRTDjIWY6Tosa4/goiqlNaUQXDzkAO6I8MKjxOK/gtNnZyfE3zAJq3Wc4Rj/JcZ8wY9vkYd3Jzv+fs2EQkbuSpcH6YXYQKHGXoUB5fs=,iv:NH+Y633dbu0ZxrBnC8I5WiEwtfZXxvsc2obNnLLZRsM=,tag:igxjHc4wkHjE6Sa1X12/+g==,type:comment]
    #ENC[AES256_GCM,data:IUEbo0cpxtF7JT9LdDj+JsD7EkIsyZU6m2hr9EZBUa38KSvqq/wTzakgy+tPhaAwfip3iG+dDIK3Rj8OOClCtjAB0GYF3VvI,iv:gy4b2Hf5fcwJVouJVAEyLQLoNwaqRsc1FTEY9Uz03+8=,tag:OI6DQUKoM9XrOkGrNuB6PQ==,type:comment]
    #ENC[AES256_GCM,data:OoAKEUIf/jMG4voVZZDroOwxcrVd3GKDCS8GlVxxIJM3ZyeX+14tNf5lP5q58xpNxaZYpys41wUvQz92CXxsJgsyTwQY3sOLc4jLggUIxHd5fPOPt8UtH+l0QxEm+ydcG3WKCEbRT1qRwwCi8/Mnp0Yy079CxT4Few==,iv:VfJKDdlcDPNIlfc98khCmfb5RyTEOU3yGjc8+c9y87s=,tag:+quMl2uWBPEHzpe+4GDVqA==,type:comment]
    #ENC[AES256_GCM,data:tgn76nVDQTTp1GMPtGNyJnYm24+yqFL9Wr4IokT/3zPFuu6kI5AebehkHEAGb9EiPk9yJq0Z6yDHZ1SpA6z3/Z1Hw6CiHPB9Fr0wXGq+FyssXtrNuyZ55AbP,iv:Z1j1NSbIgclPfwZSiH2NGk9TMeK5wYwD3Jnjqw1Kd0s=,tag:7dLZEhiRWFiszgESEGbIaA==,type:comment]
    #ENC[AES256_GCM,data:fKwW6VQ9dXMOCP33Wz1T84mm6YobHix/,iv:qxr/LLDdIEkN1BlES8/I6hz+AeTXHFwRi2RYijGjsSY=,tag:SUv/V7auzND50JeMgUKfag==,type:comment]
    davfs2: ENC[AES256_GCM,data:v5Sx1DdkbcD7N0RfvY+R/nAVOG5TOZcjPBZCSqDBg39eo4WpfRJWXrSt6YbQGuqKIgkmkxhZqCbi08sS44unimOiqU4Hm3jObFe+Pq99E8w77ugSNe6ID0ciFAioZDfobQ==,iv:/rsAeFIkA0wea3a8XaXqw6O9P32D6K9e/VQoqNX1yPY=,tag:YxukWm6ywv6ponoUGJLxKQ==,type:str]
sops:
    age:
        - recipient: age1zuv3e0rfxk35d5zryrnmaedwz7nd27sh0aq6uwua6xpu8ay7mutqe8hayp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3ZWMXMvT3I2LzBwb1pU
            amgwcFRraENyZWg0ZUpqRWJIQytoUHVoUkVjCmkvbzFtMFhVUEpBNC9ONXhoNkk5
            N1BIT0J6ZnQ2OTd6WXRwL2pPWUtlSEEKLS0tIFRqc2hzaTQvSzVsMTF1N3Nkb3RQ
            QUIwcVFVQ3Z0K1NNT0R1UE1ObGlUYTgKugZEg0K8n/vDjvQQuTWSpvEBuMgx4DqY
            QO6ymujrg4S6vq21OQT05ohgrltNFbrlPn//avADkYKu/lV17wAQgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk83u4hn7xqu0sjs82vaxzuxaw4cx7mqflz3zlr4cyd7qxw7g5dqyea5cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNU9BMjRPZHV6MU1TUHZS
            bXUrUzNZc0ticC8yMzNxb2RDbEdvSldEZVZVClRPM2JBT1BpVXNoQldnZXcydnRx
            TmJPUHpXUDFKSGRiTk9Td3pnV2Ixbk0KLS0tIFJhSlpHVnprM3VmSm5SaXgvM2lj
            dVpUVW1CRlhxWTJDVHV1RmNnVHhQdFkK3J+f+yJsU6Tz1R6+hayHkPkov+HKJy4g
            IEUQu8oNSSkJCZeKOM/qnweiG7u9GP7g59PhYIrUog9tDqMkwvODaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T14:31:31Z"
    mac: ENC[AES256_GCM,data:5x3Z+UGAw4BGOGDL8mrnWhg854Zdl/6XK68bt68xQSYbp5G2Mt7c6DscvUZXDZ4lmCcZaJjgraJ7Hyu8XGnfrWLizj04aTj9MYV7Y0l79VI9jCZEKmrIcGKoIyjywVykoZio5Dk6Gixk0t+ar93taGpCdViSZjDpsVToeeN81+Y=,iv:EkviFuKXddHLcM2+DS8ZTYk9rB0hZaYaggsJIAvKrKI=,tag:uMv9MhZ8XUkwVzWmf/dqtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
