#ENC[AES256_GCM,data:anjcB37oydkqOk1o2a/iY6T2DYwR+Ae1ZA==,iv:jyxgWtmQwBLO+pPC6U2zxkKa0TAvrD43qoR6RRBCUUE=,tag:XNgqe8wrxLj45XHr/ONsfg==,type:comment]
eduroam:
    identity: ENC[AES256_GCM,data:gqfDBlA/moDT6q311DZiPw==,iv:wswWggy5jhCG1npHjijN5I94ITMDbA84xS7EpWWGzAk=,tag:79GOA9uZmff4d41cfnOKDg==,type:str]
    password: ENC[AES256_GCM,data:TzhgM7vIX5XJsh1fm4zPqfQ9cwQC110OGewfW4c9L5OEGXYeC+ghCvPPaCYhCzGLneI=,iv:AYmVvf/cz1GpSvmyb4xT2jUlCTWtbQ3t5+H3uJVbPAE=,tag:vfVhMvGwAjYxW6cA0OFMqw==,type:str]
#ENC[AES256_GCM,data:tpU8PyOLH7kwQOj1+u2QTTSQdA==,iv:1SGVXMib3Z0wrH2QEvEdN60jcXt97HyRHn9RTtYtgpc=,tag:vYDk246CufcXKyTlhL3fBA==,type:comment]
system:
    #ENC[AES256_GCM,data:f7tgfHfQybKDrD03AQ0j/tA5mvpNLJfzOXDaaoVeaV+6VjC3rRj+58PBWmokg4H4bweqDmtlXZ0RQqL/boICje/WQEX+LTYa6yYJ7I7VZnJFz+6pb7InYA==,iv:ERwKze32QBNqBgkZc3ZUabWXQaGCd73gKkWpF6sNnsY=,tag:FmTaGECxT+ccAbO6y0QVdA==,type:comment]
    password: ENC[AES256_GCM,data:sSg9fZdP1rT5ezZ5unkmJARKbVslV1cX/iPSxm2DpMAHBCLkeknkz0vta2sMOJEzTPuSFFLH7OasZemEUvNko6gv/9f5OVKGWedQkm+FrylW01z0ZtvG+unUlbSJPgQCfN6brFIUb+3byA==,iv:aL5XqIBte+8qFCXGdwzKXehzJECpqVKoUrn2Xv1cLAE=,tag:YPYbnZ9a/HEBVeG8p+lT/A==,type:str]
sops:
    age:
        - recipient: age1zuv3e0rfxk35d5zryrnmaedwz7nd27sh0aq6uwua6xpu8ay7mutqe8hayp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3ZWMXMvT3I2LzBwb1pU
            amgwcFRraENyZWg0ZUpqRWJIQytoUHVoUkVjCmkvbzFtMFhVUEpBNC9ONXhoNkk5
            N1BIT0J6ZnQ2OTd6WXRwL2pPWUtlSEEKLS0tIFRqc2hzaTQvSzVsMTF1N3Nkb3RQ
            QUIwcVFVQ3Z0K1NNT0R1UE1ObGlUYTgKugZEg0K8n/vDjvQQuTWSpvEBuMgx4DqY
            QO6ymujrg4S6vq21OQT05ohgrltNFbrlPn//avADkYKu/lV17wAQgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk83u4hn7xqu0sjs82vaxzuxaw4cx7mqflz3zlr4cyd7qxw7g5dqyea5cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNU9BMjRPZHV6MU1TUHZS
            bXUrUzNZc0ticC8yMzNxb2RDbEdvSldEZVZVClRPM2JBT1BpVXNoQldnZXcydnRx
            TmJPUHpXUDFKSGRiTk9Td3pnV2Ixbk0KLS0tIFJhSlpHVnprM3VmSm5SaXgvM2lj
            dVpUVW1CRlhxWTJDVHV1RmNnVHhQdFkK3J+f+yJsU6Tz1R6+hayHkPkov+HKJy4g
            IEUQu8oNSSkJCZeKOM/qnweiG7u9GP7g59PhYIrUog9tDqMkwvODaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T18:48:18Z"
    mac: ENC[AES256_GCM,data:6u4OY8j/2BCVlwf+lr/gmnE4CAmvg+oalOop+UUM0duiPv76om86yX+b6yZXQcrwjUHcq8EORifIJkHTtsyEzhWgN/lNao8ZP9STMmuYkacYn7I/wWb7L0NPj3+vcfOt8623TPGB6ZkyLo4jEdl+iwQlnvz/jYnMhfXNHRLj4z0=,iv:vZJLGIoLAj/+ClJA2MzAQo+GidVPDlBNBA2mzd005uo=,tag:r4A/RQuMEwACNC8o6CGEuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
